/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "v1",
            "endpoint": "https://5cyg79qk1a.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "checkIn-dev",
            "region": "eu-central-1"
        },
        {
            "tableName": "validation-dev",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
