/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "v1",
            "endpoint": "https://5cyg79qk1a.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1",
            custom_header: async () => {
                return {Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}`}
                // Alternatively, with Cognito User Pools use this:
                // return { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` }
                // return { Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` }
            }

        }
    ],
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "validation-dev",
            "region": "eu-central-1"
        },
        {
            "tableName": "gastro-dev",
            "region": "eu-central-1"
        },
        {
            "tableName": "entry-dev",
            "region": "eu-central-1"
        },
        {
            "tableName": "qrStorage-dev",
            "region": "eu-central-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-central-1:a7d92f2e-88b2-4fe7-85fe-1c88242a52a8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_brxCRSgTn",
    "aws_user_pools_web_client_id": "7c0fj3mbd0529daf8gloevsmru",
    "oauth": {}
};


export default awsmobile;
